// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.DBContext;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Model.Analyses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ComputeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormulaVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ListingsId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MarketMedianUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("MatchSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Score")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ListingsId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("Core.Model.BodyIssues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GenerationsId")
                        .HasColumnType("uuid");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenerationsId");

                    b.ToTable("BodyIssues");
                });

            modelBuilder.Entity("Core.Model.Engine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DisplacementL")
                        .HasColumnType("numeric");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("PowerHp")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("Core.Model.EngineIssues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("AppliesYearFrom")
                        .HasColumnType("smallint");

                    b.Property<short>("AppliesYearTo")
                        .HasColumnType("smallint");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EnginesId")
                        .HasColumnType("uuid");

                    b.Property<string>("HowToCheck")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypicalMileageKm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnginesId");

                    b.ToTable("EngineIssues");
                });

            modelBuilder.Entity("Core.Model.Explanations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PowertrainsId")
                        .HasColumnType("uuid");

                    b.Property<string>("PriceBand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScoreBand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PowertrainsId");

                    b.ToTable("Explanations");
                });

            modelBuilder.Entity("Core.Model.GearBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Gears")
                        .HasColumnType("smallint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GearBoxes");
                });

            modelBuilder.Entity("Core.Model.GearboxIssues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("AppliesYearFrom")
                        .HasColumnType("smallint");

                    b.Property<short>("AppliesYearTo")
                        .HasColumnType("smallint");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GearBoxId")
                        .HasColumnType("uuid");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypicalMileageKm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GearBoxId");

                    b.ToTable("GearboxIssues");
                });

            modelBuilder.Entity("Core.Model.Generations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModelsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("YearFrom")
                        .HasColumnType("smallint");

                    b.Property<short>("YearTo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ModelsId");

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("Core.Model.Listings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AutoriaId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MileageKm")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PowertrainId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PowertrainsId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("numeric");

                    b.Property<JsonDocument>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vin")
                        .HasColumnType("text");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PowertrainsId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Core.Model.Makes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Makes");
                });

            modelBuilder.Entity("Core.Model.Models", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MakeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Core.Model.Powertrains", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Drive")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EngineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GearBoxId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenerationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SuspensionsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("GearBoxId");

                    b.HasIndex("GenerationsId");

                    b.HasIndex("SuspensionsId");

                    b.ToTable("Powertrains");
                });

            modelBuilder.Entity("Core.Model.Suspensions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suspensions");
                });

            modelBuilder.Entity("Core.Model.SuspensionsIssues", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HowToCheck")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SuspensionsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypicalMileageKm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SuspensionsId");

                    b.ToTable("SuspensionsIssues");
                });

            modelBuilder.Entity("Core.Model.Analyses", b =>
                {
                    b.HasOne("Core.Model.Listings", "Listings")
                        .WithMany()
                        .HasForeignKey("ListingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Core.Model.BodyIssues", b =>
                {
                    b.HasOne("Core.Model.Generations", "Generations")
                        .WithMany("BodyIssues")
                        .HasForeignKey("GenerationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generations");
                });

            modelBuilder.Entity("Core.Model.EngineIssues", b =>
                {
                    b.HasOne("Core.Model.Engine", "Engines")
                        .WithMany("EngineIssues")
                        .HasForeignKey("EnginesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engines");
                });

            modelBuilder.Entity("Core.Model.Explanations", b =>
                {
                    b.HasOne("Core.Model.Powertrains", "Powertrains")
                        .WithMany("Explanations")
                        .HasForeignKey("PowertrainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Powertrains");
                });

            modelBuilder.Entity("Core.Model.GearboxIssues", b =>
                {
                    b.HasOne("Core.Model.GearBox", "GearBox")
                        .WithMany("GearboxIssues")
                        .HasForeignKey("GearBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GearBox");
                });

            modelBuilder.Entity("Core.Model.Generations", b =>
                {
                    b.HasOne("Core.Model.Models", "Models")
                        .WithMany("Generations")
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Models");
                });

            modelBuilder.Entity("Core.Model.Listings", b =>
                {
                    b.HasOne("Core.Model.Powertrains", "Powertrains")
                        .WithMany("Listings")
                        .HasForeignKey("PowertrainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Powertrains");
                });

            modelBuilder.Entity("Core.Model.Models", b =>
                {
                    b.HasOne("Core.Model.Makes", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("Core.Model.Powertrains", b =>
                {
                    b.HasOne("Core.Model.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Model.GearBox", "GearBox")
                        .WithMany()
                        .HasForeignKey("GearBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Model.Generations", "Generations")
                        .WithMany()
                        .HasForeignKey("GenerationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Model.Suspensions", "Suspensions")
                        .WithMany()
                        .HasForeignKey("SuspensionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("GearBox");

                    b.Navigation("Generations");

                    b.Navigation("Suspensions");
                });

            modelBuilder.Entity("Core.Model.SuspensionsIssues", b =>
                {
                    b.HasOne("Core.Model.Suspensions", "Suspensions")
                        .WithMany("SuspensionsIssues")
                        .HasForeignKey("SuspensionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suspensions");
                });

            modelBuilder.Entity("Core.Model.Engine", b =>
                {
                    b.Navigation("EngineIssues");
                });

            modelBuilder.Entity("Core.Model.GearBox", b =>
                {
                    b.Navigation("GearboxIssues");
                });

            modelBuilder.Entity("Core.Model.Generations", b =>
                {
                    b.Navigation("BodyIssues");
                });

            modelBuilder.Entity("Core.Model.Makes", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Core.Model.Models", b =>
                {
                    b.Navigation("Generations");
                });

            modelBuilder.Entity("Core.Model.Powertrains", b =>
                {
                    b.Navigation("Explanations");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Core.Model.Suspensions", b =>
                {
                    b.Navigation("SuspensionsIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
